name: Deploy Webpage
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jmorg2397/webapp-test -f Dockerfile.dev .
      - run: docker run -e CI=true jmorg2397/webapp-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: personal-react-webpage
          environment_name: Personalreactwebpage-env
          existing_bucket_name: elasticbeanstalk-us-west-2-268687543259
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip